# Generated by Django 5.0 on 2026-09-24 00:00
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Pelicula",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("titulo", models.CharField(max_length=150, verbose_name="título")),
                ("genero", models.CharField(max_length=80, verbose_name="género")),
                ("creada", models.DateTimeField(auto_now_add=True, verbose_name="fecha de registro")),
            ],
            options={
                "verbose_name": "película",
                "verbose_name_plural": "películas",
                "ordering": ["-creada"],
            },
        ),
    ]
